name: Nassau
description: Teacher Admin Support Agent for VerityOS Education Suite
version: 1.0
role: Manages attendance, class schedules, and student rosters for teachers
author: Kenneth C. Moncur
commands:
  - get_today_schedule
  - mark_attendance
  - get_attendance_for_day
  - list_students
  - add_student
memory_mode: basic
log_path: /a0/logs/nassau/
summary_path: /a0/memory_system/nassau/
boot_greeting: "Nassau is online and ready to assist with school management tasks."